#extension of test.R
#calling essential libraries
install.packages( c("arules","readr"),dependencies = TRUE)
library(XML)
library(rjson)
library(jsonlite)
library(data.table)
library(splitstackshape)
library(stringr)
library(plyr)
library(dplyr)

cleanmerge <- lapply(mergedata$value.x, gsub,pattern= '<span class="fsprebig fn1bold">', replacement ="")
gc()
cleanmerge <- data.frame(cleanmerge)
gc()
cleanmerge <- lapply(cleanmerge, gsub,pattern= '<span></span>', replacement ="")
gc()
cleanmerge <- data.frame(cleanmerge)
gc()
cleanmerge <- lapply(cleanmerge, gsub,pattern= '</span><br>', replacement ="")
gc()
cleanmerge <- data.frame(cleanmerge)
gc()
cleanmerge <- lapply(cleanmerge, gsub,pattern= '<strong>', replacement ="")
gc()
cleanmerge <- data.frame(cleanmerge)
gc()
cleanmerge <- lapply(cleanmerge, gsub,pattern= '</strong>', replacement ="")
gc()
cleanmerge <- data.frame(cleanmerge)
gc()
cleanmerge <- lapply(cleanmerge, gsub,pattern= '&nbsp;', replacement ="")
gc()
cleanmerge <- data.frame(cleanmerge)
gc()
cleanmerge <- lapply(cleanmerge, gsub,pattern= '<span>', replacement ="")
gc()
cleanmerge <- data.frame(cleanmerge)
gc()
cleanmerge <- lapply(cleanmerge, gsub,pattern= '</span>', replacement ="")
gc()
cleanmerge <- data.frame(cleanmerge)
gc()

